# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SXJFRAC_MVVMDEMO' do

  pod 'ReactiveObjC'
  #pod 'MLeaksFinder'


  target 'SXJFRAC_MVVMDEMOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SXJFRAC_MVVMDEMOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
